# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drugFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=100)),
                ('featureName', models.CharField(max_length=100)),
                ('drugFeature', models.TextField()),
            ],
        ),
    ]
