# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugApp', '0002_drugfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugByname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugClass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugname',
            field=models.CharField(max_length=100),
        ),
    ]
