# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugApp', '0002_drugfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlldrugNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=200)),
                ('drugArticle', models.CharField(max_length=200)),
                ('drugKnowledgeRef', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='drugNames',
            fields=[
                ('drugname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='drugUrl',
            fields=[
                ('drugUrl', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UrlDescribe', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugByname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugClass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='alldrugnames',
            unique_together=set([('drugname', 'drugArticle')]),
        ),
    ]
