# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugApp', '0004_drugfeature_drugfeaturekeywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugfeature',
            old_name='drugFeature',
            new_name='drugFeatureContent',
        ),
    ]
