# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugApp', '0004_drugurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='drugNames',
            fields=[
                ('drugname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
